import {
  StudentProfile,
  SkillLevel,
  WorkMode,
  RelocationPreference,
  AvailabilityOption,
  WorkType,
  ModerationStatus,
  CompanyProfile,
  CompanyVerificationStatus,
  RecruiterProfile,
  UserRole,
  PaymentStatus,
  PaymentRecord,
} from '@fresher2work/types';

export const INITIAL_COMPANIES: CompanyProfile[] = [
  {
    id: 'comp-1',
    name: 'RazorScale Technologies',
    website: 'https://razorscale.io',
    logoUrl: 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=128&auto=format&fit=crop&q=80',
    location: 'Bengaluru, Karnataka',
    industry: 'FinTech & B2B SaaS',
    verificationStatus: CompanyVerificationStatus.VERIFIED,
  },
  {
    id: 'comp-2',
    name: 'NovaCloud Systems',
    website: 'https://novacloud.dev',
    logoUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=128&auto=format&fit=crop&q=80',
    location: 'Hyderabad, Telangana',
    industry: 'Cloud Infrastructure & AI',
    verificationStatus: CompanyVerificationStatus.VERIFIED,
  },
  {
    id: 'comp-3',
    name: 'KiteHealth Labs',
    website: 'https://kitehealth.in',
    logoUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=128&auto=format&fit=crop&q=80',
    location: 'Kochi, Kerala',
    industry: 'Digital HealthTech',
    verificationStatus: CompanyVerificationStatus.VERIFIED,
  },
];

export const INITIAL_RECRUITERS: RecruiterProfile[] = [
  {
    id: 'rec-1',
    userId: 'user-rec-1',
    fullName: 'Anjali Menon',
    designation: 'Lead Technical Recruiter',
    businessEmail: 'anjali.m@razorscale.io',
    linkedinUrl: 'https://linkedin.com/in/anjalimenon-hr',
    companyId: 'comp-1',
    company: INITIAL_COMPANIES[0],
  },
  {
    id: 'rec-2',
    userId: 'user-rec-2',
    fullName: 'Vikram Joshi',
    designation: 'Engineering Talent Partner',
    businessEmail: 'vikram@novacloud.dev',
    linkedinUrl: 'https://linkedin.com/in/vikram-talent',
    companyId: 'comp-2',
    company: INITIAL_COMPANIES[1],
  },
];

export const INITIAL_STUDENTS: StudentProfile[] = [
  {
    id: 'student-1',
    userId: 'user-stu-1',
    fullName: 'Rohan Sharma',
    email: 'rohan.sharma.dev@gmail.com',
    phone: '+91 98765 43210',
    headline: 'Full-Stack Developer | React, Node.js & TypeScript Enthusiast',
    about: 'Computer Science graduate (2025) with a passion for building high-performance, real-time web applications. Built 3 end-to-end full-stack projects including a collaborative Kanban board and an automated invoice generator.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    cvFileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    cvUploadedAt: new Date().toISOString(),
    githubUrl: 'https://github.com/rohansharma-dev',
    linkedinUrl: 'https://linkedin.com/in/rohansharma-dev',
    portfolioUrl: 'https://rohansharma.me',
    completenessScore: 95,
    isActivated: true,
    activatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    moderationStatus: ModerationStatus.APPROVED,
    publicSlug: 'rohan-sharma',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    education: [
      {
        id: 'edu-1',
        studentId: 'student-1',
        institutionName: 'National Institute of Technology, Calicut',
        degree: 'B.Tech',
        fieldOfStudy: 'Computer Science and Engineering',
        startYear: 2021,
        endYear: 2025,
        gradeOrCgpa: '8.8 CGPA',
      },
    ],
    projects: [
      {
        id: 'proj-1',
        studentId: 'student-1',
        title: 'TaskFlow — Real-Time Collaborative Project Board',
        description: 'A full-stack Kanban board featuring drag-and-drop task ordering, WebSocket live synchronization, multi-user presence avatars, and activity logs.',
        role: 'Lead Full-Stack Developer',
        toolsUsed: ['Figma', 'VS Code', 'Postman', 'Docker'],
        skillsDemonstrated: ['Real-Time State Sync', 'Optimistic UI Updates', 'REST API Design'],
        projectLink: 'https://taskflow-demo.vercel.app',
        liveDemoUrl: 'https://taskflow-demo.vercel.app',
        githubRepoUrl: 'https://github.com/rohansharma-dev/taskflow',
        mediaUrls: [
          'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format&fit=crop&q=80',
        ],
        techStack: ['React', 'TypeScript', 'Node.js', 'Socket.io', 'PostgreSQL', 'Tailwind CSS'],
        orderIndex: 0,
      },
      {
        id: 'proj-2',
        studentId: 'student-1',
        title: 'BillCraft — Automated GST Invoice Generator',
        description: 'Micro-SaaS allowing Indian freelancers to generate compliant GST invoices with automated PDF rendering and payment QR code integration.',
        role: 'Full-Stack Developer',
        toolsUsed: ['Figma', 'Prisma Studio'],
        skillsDemonstrated: ['PDF Generation', 'Database Indexing', 'Payment Webhook Idempotency'],
        projectLink: 'https://billcraft.vercel.app',
        liveDemoUrl: 'https://billcraft.vercel.app',
        githubRepoUrl: 'https://github.com/rohansharma-dev/billcraft',
        mediaUrls: [
          'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80',
        ],
        techStack: ['Next.js', 'Prisma', 'Tailwind CSS', 'Razorpay API'],
        orderIndex: 1,
      },
    ],
    workSamples: [],
    skills: [
      { id: 'sk-1', studentId: 'student-1', skillName: 'React', proficiencyLevel: SkillLevel.ADVANCED, isVerified: true },
      { id: 'sk-2', studentId: 'student-1', skillName: 'TypeScript', proficiencyLevel: SkillLevel.ADVANCED, isVerified: true },
      { id: 'sk-3', studentId: 'student-1', skillName: 'Node.js', proficiencyLevel: SkillLevel.INTERMEDIATE, isVerified: true },
      { id: 'sk-4', studentId: 'student-1', skillName: 'PostgreSQL', proficiencyLevel: SkillLevel.INTERMEDIATE, isVerified: false },
      { id: 'sk-5', studentId: 'student-1', skillName: 'Tailwind CSS', proficiencyLevel: SkillLevel.ADVANCED, isVerified: true },
    ],
    certificates: [
      {
        id: 'cert-1',
        studentId: 'student-1',
        name: 'Meta Front-End Developer Professional Certificate',
        issuingOrganization: 'Coursera / Meta',
        issueDate: '2024-08-15',
        credentialUrl: 'https://coursera.org/verify/meta/rohansharma',
      },
    ],
    preferences: {
      id: 'pref-1',
      studentId: 'student-1',
      preferredRoles: ['Full-Stack Developer', 'Frontend Engineer', 'React Developer'],
      preferredIndustries: ['IT & Software', 'FinTech', 'E-Commerce'],
      preferredLocations: ['Bengaluru', 'Hyderabad', 'Kochi', 'Remote'],
      preferredCountries: ['India', 'United Arab Emirates'],
      workModes: [WorkMode.HYBRID, WorkMode.REMOTE],
      workMode: WorkMode.HYBRID,
      relocationWillingness: RelocationPreference.WILLING,
      availability: AvailabilityOption.IMMEDIATE,
      preferredWorkTypes: [WorkType.FULL_TIME, WorkType.INTERNSHIP],
      expectedSalaryMin: 500000,
      salaryCurrency: 'INR',
    },
  },
  {
    id: 'student-2',
    userId: 'user-stu-2',
    fullName: 'Pooja Nair',
    email: 'pooja.nair.ai@gmail.com',
    phone: '+91 97456 12389',
    headline: 'AI & Data Science Fresher | Python, PyTorch & FastAPIs',
    about: 'Passionate about machine learning and data engineering. Built a disease classification vision model (96% accuracy on test set) and scalable FastAPI prediction microservices.',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    cvFileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    cvUploadedAt: new Date().toISOString(),
    githubUrl: 'https://github.com/poojanair-ai',
    linkedinUrl: 'https://linkedin.com/in/poojanair-ai',
    portfolioUrl: 'https://poojanair.dev',
    completenessScore: 90,
    isActivated: true,
    activatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    moderationStatus: ModerationStatus.APPROVED,
    publicSlug: 'pooja-nair',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    education: [
      {
        id: 'edu-2',
        studentId: 'student-2',
        institutionName: 'College of Engineering, Trivandrum (CET)',
        degree: 'B.Tech',
        fieldOfStudy: 'Artificial Intelligence & Data Science',
        startYear: 2021,
        endYear: 2025,
        gradeOrCgpa: '9.1 CGPA',
      },
    ],
    projects: [
      {
        id: 'proj-3',
        studentId: 'student-2',
        title: 'MedVision — Chest X-Ray Pathology Classifier',
        description: 'Deep learning pipeline utilizing EfficientNet with Grad-CAM visual heatmaps deployed via FastAPI and Docker for instant medical radiology insights.',
        role: 'Lead ML Engineer',
        toolsUsed: ['PyTorch', 'Docker', 'FastAPI', 'W&B'],
        skillsDemonstrated: ['Model Training', 'Grad-CAM Interpretability', 'Containerization'],
        projectLink: 'https://medvision-demo.hf.space',
        liveDemoUrl: 'https://medvision-demo.hf.space',
        githubRepoUrl: 'https://github.com/poojanair-ai/medvision',
        mediaUrls: [
          'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&auto=format&fit=crop&q=80',
        ],
        techStack: ['Python', 'PyTorch', 'FastAPI', 'Docker', 'HuggingFace', 'Pandas'],
        orderIndex: 0,
      },
    ],
    workSamples: [],
    skills: [
      { id: 'sk-6', studentId: 'student-2', skillName: 'Python', proficiencyLevel: SkillLevel.ADVANCED, isVerified: true },
      { id: 'sk-7', studentId: 'student-2', skillName: 'PyTorch', proficiencyLevel: SkillLevel.INTERMEDIATE, isVerified: true },
      { id: 'sk-8', studentId: 'student-2', skillName: 'FastAPI', proficiencyLevel: SkillLevel.INTERMEDIATE, isVerified: true },
      { id: 'sk-9', studentId: 'student-2', skillName: 'SQL', proficiencyLevel: SkillLevel.INTERMEDIATE, isVerified: false },
      { id: 'sk-10', studentId: 'student-2', skillName: 'Docker', proficiencyLevel: SkillLevel.BEGINNER, isVerified: false },
    ],
    certificates: [
      {
        id: 'cert-2',
        studentId: 'student-2',
        name: 'Deep Learning Specialization',
        issuingOrganization: 'DeepLearning.AI',
        issueDate: '2024-04-10',
        credentialUrl: 'https://coursera.org/verify/deeplearning/pooja',
      },
    ],
    preferences: {
      id: 'pref-2',
      studentId: 'student-2',
      preferredRoles: ['AI Engineer', 'Data Scientist', 'Machine Learning Engineer'],
      preferredIndustries: ['IT & Software', 'Healthcare', 'FinTech'],
      preferredLocations: ['Bengaluru', 'Kochi', 'Remote'],
      preferredCountries: ['India', 'United Arab Emirates', 'Singapore'],
      workModes: [WorkMode.REMOTE, WorkMode.HYBRID],
      workMode: WorkMode.REMOTE,
      relocationWillingness: RelocationPreference.WILLING,
      availability: AvailabilityOption.IMMEDIATE,
      preferredWorkTypes: [WorkType.FULL_TIME, WorkType.INTERNSHIP],
      expectedSalaryMin: 600000,
      salaryCurrency: 'INR',
    },
  },
  {
    id: 'student-3',
    userId: 'user-stu-3',
    fullName: 'Aditya Verma',
    email: 'aditya.verma.mobile@gmail.com',
    phone: '+91 99887 66554',
    headline: 'Flutter & React Native Developer | 2 Published Apps',
    about: 'Mobile engineer focused on smooth 60fps animations, intuitive offline-first UX, and clean architecture (Riverpod & Zustand).',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    cvFileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    cvUploadedAt: new Date().toISOString(),
    githubUrl: 'https://github.com/adityaverma-apps',
    linkedinUrl: 'https://linkedin.com/in/adityaverma-mobile',
    portfolioUrl: 'https://aditya.flutterdev.in',
    completenessScore: 85,
    isActivated: true,
    activatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    moderationStatus: ModerationStatus.APPROVED,
    publicSlug: 'aditya-verma',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    education: [
      {
        id: 'edu-3',
        studentId: 'student-3',
        institutionName: 'Vellore Institute of Technology (VIT)',
        degree: 'B.Tech',
        fieldOfStudy: 'Information Technology',
        startYear: 2021,
        endYear: 2025,
        gradeOrCgpa: '8.4 CGPA',
      },
    ],
    projects: [
      {
        id: 'proj-4',
        studentId: 'student-3',
        title: 'HabitZen — Minimalist Offline-First Habit Tracker',
        description: 'Cross-platform mobile habit builder with custom interactive heatmaps, local notifications, and SQLite biometric locking.',
        role: 'Solo Mobile Developer',
        toolsUsed: ['Figma', 'Android Studio', 'Xcode'],
        skillsDemonstrated: ['Offline First Storage', 'Biometric Authentication', 'Cross Platform UI'],
        projectLink: 'https://play.google.com/store/apps/details?id=demo.habitzen',
        liveDemoUrl: 'https://play.google.com/store/apps/details?id=demo.habitzen',
        githubRepoUrl: 'https://github.com/adityaverma-apps/habitzen',
        mediaUrls: [
          'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&auto=format&fit=crop&q=80',
        ],
        techStack: ['Flutter', 'Dart', 'SQLite', 'Riverpod', 'Firebase'],
        orderIndex: 0,
      },
    ],
    workSamples: [],
    skills: [
      { id: 'sk-11', studentId: 'student-3', skillName: 'Flutter', proficiencyLevel: SkillLevel.ADVANCED, isVerified: true },
      { id: 'sk-12', studentId: 'student-3', skillName: 'Dart', proficiencyLevel: SkillLevel.ADVANCED, isVerified: true },
      { id: 'sk-13', studentId: 'student-3', skillName: 'React Native', proficiencyLevel: SkillLevel.INTERMEDIATE, isVerified: false },
      { id: 'sk-14', studentId: 'student-3', skillName: 'Firebase', proficiencyLevel: SkillLevel.INTERMEDIATE, isVerified: true },
    ],
    certificates: [],
    preferences: {
      id: 'pref-3',
      studentId: 'student-3',
      preferredRoles: ['Flutter Developer', 'React Native Developer', 'Mobile App Engineer'],
      preferredIndustries: ['IT & Software', 'Design & Creative Media', 'E-Commerce'],
      preferredLocations: ['Bengaluru', 'Chennai', 'Pune', 'Remote'],
      preferredCountries: ['India'],
      workModes: [WorkMode.REMOTE, WorkMode.HYBRID, WorkMode.ON_SITE],
      workMode: WorkMode.ANY,
      relocationWillingness: RelocationPreference.DOMESTIC_ONLY,
      availability: AvailabilityOption.WITHIN_15_DAYS,
      preferredWorkTypes: [WorkType.FULL_TIME, WorkType.CONTRACT],
      expectedSalaryMin: 450000,
      salaryCurrency: 'INR',
    },
  },
  {
    id: 'student-4',
    userId: 'user-stu-4',
    fullName: 'Meera Krishnan',
    email: 'meera.designs@gmail.com',
    phone: '+91 94471 23456',
    headline: 'Product & UI/UX Designer | Design Systems & Micro-Interactions',
    about: 'Design graduate focused on intuitive human-centered interfaces, accessible design systems, and rapid interactive prototyping in Figma.',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    cvFileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    cvUploadedAt: new Date().toISOString(),
    portfolioUrl: 'https://meerakrishnandesign.com',
    linkedinUrl: 'https://linkedin.com/in/meerakrishnan-ux',
    completenessScore: 92,
    isActivated: true,
    activatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    moderationStatus: ModerationStatus.APPROVED,
    publicSlug: 'meera-krishnan',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    education: [
      {
        id: 'edu-4',
        studentId: 'student-4',
        institutionName: 'National Institute of Design (NID)',
        degree: 'B.Des',
        fieldOfStudy: 'Interaction Design',
        startYear: 2021,
        endYear: 2025,
        gradeOrCgpa: '8.9 CGPA',
      },
    ],
    projects: [
      {
        id: 'proj-5',
        studentId: 'student-4',
        title: 'FinEase — Accessible Mobile Banking for Seniors',
        description: 'Comprehensive end-to-end UX case study with 15 user interviews, wireframing, high-contrast accessible design tokens, and usability testing.',
        role: 'Lead UI/UX Designer',
        toolsUsed: ['Figma', 'FigJam', 'Principle', 'Miro'],
        skillsDemonstrated: ['User Research', 'Accessibility (WCAG AAA)', 'Design Tokens'],
        projectLink: 'https://www.behance.net/gallery/finease-banking',
        liveDemoUrl: 'https://www.figma.com/proto/finease-mockup',
        mediaUrls: [
          'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&auto=format&fit=crop&q=80',
        ],
        techStack: ['Figma', 'Design Systems', 'User Research', 'Wireframing'],
        orderIndex: 0,
      },
    ],
    workSamples: [
      {
        id: 'ws-1',
        studentId: 'student-4',
        title: 'SaaS Analytics Dashboard UI Kit',
        category: 'GRAPHIC_DESIGN' as any,
        description: 'Complete 40+ component design kit for dark-mode data analytics platforms with custom chart visual styles.',
        mediaUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80'],
        workLink: 'https://dribbble.com/shots/saas-dashboard-kit',
        clientOrContext: 'Open Source Community Asset',
        toolsUsed: ['Figma', 'Illustrator'],
        orderIndex: 0,
        createdAt: new Date().toISOString(),
      },
    ],
    skills: [
      { id: 'sk-15', studentId: 'student-4', skillName: 'Figma', proficiencyLevel: SkillLevel.ADVANCED, isVerified: true },
      { id: 'sk-16', studentId: 'student-4', skillName: 'UI Design', proficiencyLevel: SkillLevel.ADVANCED, isVerified: true },
      { id: 'sk-17', studentId: 'student-4', skillName: 'UX Research', proficiencyLevel: SkillLevel.INTERMEDIATE, isVerified: true },
      { id: 'sk-18', studentId: 'student-4', skillName: 'Design Systems', proficiencyLevel: SkillLevel.ADVANCED, isVerified: true },
    ],
    certificates: [
      {
        id: 'cert-3',
        studentId: 'student-4',
        name: 'Google UX Design Professional Certificate',
        issuingOrganization: 'Google / Coursera',
        issueDate: '2024-05-20',
        credentialUrl: 'https://coursera.org/verify/google-ux/meera',
      },
    ],
    preferences: {
      id: 'pref-4',
      studentId: 'student-4',
      preferredRoles: ['UI/UX Designer', 'Product Designer', 'Interaction Designer'],
      preferredIndustries: ['Design & Creative Media', 'FinTech', 'IT & Software'],
      preferredLocations: ['Kochi', 'Kozhikode', 'Bengaluru', 'Dubai', 'Remote'],
      preferredCountries: ['India', 'United Arab Emirates'],
      workModes: [WorkMode.REMOTE, WorkMode.HYBRID],
      workMode: WorkMode.REMOTE,
      relocationWillingness: RelocationPreference.WILLING,
      availability: AvailabilityOption.IMMEDIATE,
      preferredWorkTypes: [WorkType.FULL_TIME, WorkType.CONTRACT],
      expectedSalaryMin: 480000,
      salaryCurrency: 'INR',
    },
  },
  {
    id: 'student-5',
    userId: 'user-stu-5',
    fullName: 'Farhan Tariq',
    email: 'farhan.growth@gmail.com',
    phone: '+971 50 123 4567',
    headline: 'Digital Marketing & SEO Strategist | Performance Ads & Content',
    about: 'Digital marketing graduate with real track record running Google Search campaigns (3.4x ROAS) and SEO content clusters achieving 40k monthly organic visits.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    cvFileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    cvUploadedAt: new Date().toISOString(),
    linkedinUrl: 'https://linkedin.com/in/farhantariq-mkt',
    portfolioUrl: 'https://farhangrowth.com',
    completenessScore: 88,
    isActivated: true,
    activatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    moderationStatus: ModerationStatus.APPROVED,
    publicSlug: 'farhan-tariq',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    education: [
      {
        id: 'edu-5',
        studentId: 'student-5',
        institutionName: 'University of Dubai',
        degree: 'BBA',
        fieldOfStudy: 'Marketing & Digital Media',
        startYear: 2021,
        endYear: 2025,
        gradeOrCgpa: '3.7 GPA',
      },
    ],
    projects: [],
    workSamples: [
      {
        id: 'ws-2',
        studentId: 'student-5',
        title: 'E-Commerce Launch SEO & Meta Ads Campaign',
        category: 'CAMPAIGN' as any,
        description: 'Structured 12 search ad groups, optimized negative keyword list, and wrote high-converting ad copies generating AED 85,000 in first quarter.',
        mediaUrls: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80'],
        workLink: 'https://farhangrowth.com/case-studies/ecommerce-launch',
        clientOrContext: 'Local D2C Brand Client',
        toolsUsed: ['Google Ads', 'Meta Ads Manager', 'Ahrefs', 'Google Analytics 4'],
        orderIndex: 0,
        createdAt: new Date().toISOString(),
      },
    ],
    skills: [
      { id: 'sk-19', studentId: 'student-5', skillName: 'SEO', proficiencyLevel: SkillLevel.ADVANCED, isVerified: true },
      { id: 'sk-20', studentId: 'student-5', skillName: 'Google Ads', proficiencyLevel: SkillLevel.ADVANCED, isVerified: true },
      { id: 'sk-21', studentId: 'student-5', skillName: 'Content Marketing', proficiencyLevel: SkillLevel.INTERMEDIATE, isVerified: true },
      { id: 'sk-22', studentId: 'student-5', skillName: 'Google Analytics 4', proficiencyLevel: SkillLevel.ADVANCED, isVerified: true },
    ],
    certificates: [
      {
        id: 'cert-4',
        studentId: 'student-5',
        name: 'Google Ads Search Certification',
        issuingOrganization: 'Google Skillshop',
        issueDate: '2024-06-12',
        credentialUrl: 'https://skillshop.credential.net/google-ads-search',
      },
    ],
    preferences: {
      id: 'pref-5',
      studentId: 'student-5',
      preferredRoles: ['Digital Marketing Executive', 'SEO Specialist', 'Performance Marketer'],
      preferredIndustries: ['Marketing & Advertising', 'E-Commerce', 'FinTech'],
      preferredLocations: ['Dubai', 'Abu Dhabi', 'Kochi', 'Bengaluru', 'Remote'],
      preferredCountries: ['United Arab Emirates', 'India'],
      workModes: [WorkMode.ON_SITE, WorkMode.HYBRID, WorkMode.REMOTE],
      workMode: WorkMode.HYBRID,
      relocationWillingness: RelocationPreference.WILLING,
      availability: AvailabilityOption.IMMEDIATE,
      preferredWorkTypes: [WorkType.FULL_TIME],
      expectedSalaryMin: 800000,
      salaryCurrency: 'INR',
    },
  },
  {
    id: 'student-unactivated',
    userId: 'user-stu-unact',
    fullName: 'Unactivated Student',
    email: 'unactivated@example.com',
    phone: '+91 91111 22222',
    headline: 'Aspiring Web Developer',
    about: 'Incomplete profile that has not paid ₹99 activation fee.',
    completenessScore: 40,
    isActivated: false,
    moderationStatus: ModerationStatus.APPROVED,
    publicSlug: 'unactivated-student',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    education: [],
    projects: [],
    workSamples: [],
    skills: [],
    certificates: [],
  },
  {
    id: 'student-pending-moderation',
    userId: 'user-stu-pending',
    fullName: 'Pending Review Student',
    email: 'pending@example.com',
    phone: '+91 93333 44444',
    headline: 'Backend Developer',
    about: 'Activated but moderation status is pending review.',
    completenessScore: 80,
    isActivated: true,
    moderationStatus: ModerationStatus.PENDING_REVIEW,
    publicSlug: 'pending-student',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    education: [],
    projects: [],
    workSamples: [],
    skills: [],
    certificates: [],
  },
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-1',
    studentId: 'student-1',
    gatewayOrderId: 'order_FTW_1001',
    gatewayPaymentId: 'pay_FTW_882193',
    amountPaise: 9900,
    currency: 'INR',
    status: PaymentStatus.SUCCESS,
    signature: 'sig_verified_hmac_sha256_mock_001',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    verifiedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'pay-2',
    studentId: 'student-2',
    gatewayOrderId: 'order_FTW_1002',
    gatewayPaymentId: 'pay_FTW_882194',
    amountPaise: 9900,
    currency: 'INR',
    status: PaymentStatus.SUCCESS,
    signature: 'sig_verified_hmac_sha256_mock_002',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    verifiedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'pay-3',
    studentId: 'student-3',
    gatewayOrderId: 'order_FTW_1003',
    gatewayPaymentId: 'pay_FTW_882195',
    amountPaise: 9900,
    currency: 'INR',
    status: PaymentStatus.SUCCESS,
    signature: 'sig_verified_hmac_sha256_mock_003',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    verifiedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
